# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Malware
version:      1.00
version_from: lib/Malware.pm
installdirs:  site
requires:
    Archive::Extract:              
    Class::ParmList:               
    Net::Connection::Simple:       1
    Net::Protocol::Simple:         1
    Text::Table:                   1.107
    Time::Timestamp:               1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
